### ISSUE TITLE
Junk <![CDATA[YII-BLOCK-HEAD]]> code around email template

### ISSUE THREAD

**Issue by iparr** [putyourlightson/craft-campaign#337]
This has been working fine for months, but just since Craft v4 (I think) this error has crept in.

I'm sending a regular scheduled email every week and it pulls in a template.

In preview this looks fine, but when emailed I get:
```
<
![CDATA[YII-BLOCK-HEAD]]>
<![CDATA[YII-BLOCK-BODY-BEGIN]]>
```

…and then:
```
<![CDATA[YII-BLOCK-BODY-END]]>
```

…at the end of the email.

Why is this appearing and how am I able to hide it (again!)?

In my template I have:
```
		<!--[if gte mso 9]>
		<xml>
			<o:OfficeDocumentSettings>
			<o:AllowPNG/>
			<o:PixelsPerInch>96</o:PixelsPerInch>
			</o:OfficeDocumentSettings>
		</xml>
		<![endif]-->
	</head>
	<body yahoo bgcolor="{{ color.background_white }}" style="margin:0;padding:0;word-spacing:normal;background-color:{{ color.background_white }};">
	<div role="article" aria-roledescription="email" lang="en" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:{{ color.background_white }};">
```

But in my email message raw source I get:
```
<!--[if gte mso 9]>
		<xml>
			<o:OfficeDocumentSettings>
			<o:AllowPNG/>
			<o:PixelsPerInch>96</o:PixelsPerInch>
			</o:OfficeDocumentSettings>
		</xml>
		<![endif]-->
	&lt;</head><body><p>![CDATA[YII-BLOCK-HEAD]]&gt;
	</p>&lt;![CDATA[YII-BLOCK-BODY-BEGIN]]&gt;
	<div role=3D"article" aria-roledescription=3D"email" lang=3D"en" style=3D"=-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;background-color:#f=ffffe;">
```

**Comment by bencroker** [comment]
There's a branch in progress to address this at https://github.com/putyourlightson/craft-campaign/tree/bugfix/yii-blocks, which a few people are in the process of testing. If you could test as well then that would help speed up the fix.

**Comment by iparr** [comment]
I have tried, but it renders the `admin/campaign/sendouts/recurring/preview/xxxxxx` page without CSS or JS (the rest of the Dashboard is fine), so I can't send a test email. Don't want to add fuel to the fire, I may have to sit this one out!

**Comment by bencroker** [comment]
How are you inserting the CSS and JS?

In the meantime, clearing `Compiled templates` in the `Caches` utility should fix the issue, albeit temporarily.

<img width="235" alt="Screenshot 2022-10-27 at 20 04 05" src="https://user-images.githubusercontent.com/57572400/198428630-06fba69b-855f-48c5-83eb-3667db582937.png">

**Comment by bencroker** [comment]
Ah, you meant that CSS and JS were missing from the sendout edit page. I've fixed that in https://github.com/putyourlightson/craft-campaign/commit/e30ff4369f1408dd70dd024abcf996b5e08e10e7, can you please run `composer update` and try again?

**Comment by iparr** [comment]
First the good news:

1. That Dashboard page now renders correctly.
2. A test of the email sends through one that looks as it did and without the `<!CDATA[YII`… code.

The bad news:

1. The preview pane ("HTML Body") now injects in a lot of CSS that was not there previously and so the template looks very different to the one that is actually sent through via email. For example:

`main.css` provides:
```
.header, .hud-header {
    border-radius: var(--large-border-radius) var(--large-border-radius) 0 0;
    box-shadow: inset 0 -1px 0 var(--hairline-color);
    padding: 24px;
}
```

This wasn't there before, the view within this pane was completely isolated from any other styling.

(I am clearing my caches before any test)

**Comment by bencroker** [comment]
> The preview pane ("HTML Body") now injects in a lot of CSS that was not there previously and so the template looks very different to the one that is actually sent through via email.

Good catch, those are CP assets being injected, fixed in https://github.com/putyourlightson/craft-campaign/commit/35bc198e3791ee36ce1004bd8c9df696c051140f.

**Comment by iparr** [comment]
👍 Can confirm, it's now fixed with respect to all these things.

**Comment by bencroker** [comment]
Excellent, thanks for helping test this!

**Comment by bencroker** [comment]
Released in version 2.2.0.

**Comment by BAM-Dennis** [comment]
@bencroker  any chance you can also migrate it back to 1.x version for craft 3 support? i am still having this issue

**Comment by bencroker** [comment]
Yes, I'll backport this fix for v1.

**Comment by bencroker** [comment]
Released in version 1.24.0.
