### ISSUE TITLE
Import into new mail list throws error

### ISSUE THREAD

**Issue by robinbeatty** [putyourlightson/craft-campaign#349]
Craft 4.3.4
Campaign Lite 2.2.3
DDEV

This is after an upgrade to Craft 4 (before a working instance of Campaign was running on Craft 3)

Issue:
When creating a new mail list, then in /admin/campaign/contacts choosing the 'import' tab, an error is thrown as below:

Impossible to access an attribute ("title") on a null variable.
...
{% set tableData = tableData|merge([{
        id: import.id,
        title: import.fileName ? 'CSV File'|t('campaign') : 'User Group'|t('campaign'),
        url: import.cpViewUrl,
        source: source,
        mailingList: tag('a', {
            text: mailingList.title, <----------------- error
            href: mailingList.cpEditUrl,
            class: 'go',
            target: '_blank',
        }),
        forceSubscribe: forms.lightswitch({
            on: import.forceSubscribe,
            disabled: true,
        }),
        added: import.added,

...

In fact any way into the import tab fails like this.

Another issue:
When selecting a contact entry ( /admin/campaign/contacts/12345 ) craft throws an error in `vendor/putyourlightson/craft-campaign/src/templates/reports/contacts/_includes/campaign-activity.twig:35`

"Variable "contactId" does not exist."
...
 {% if limit is defined and limit == campaignActivity|length %}
        <p><a href="{{ url('campaign/reports/contacts/' ~ contactId ~ '/campaign-activity') }}" class="go">{{ "View all"|t('campaign') }}</a></p>
 {% endif %}
...

This strangely only seems to happen with *some* contacts. Others behave as expected.

I've checked the craft_campaign_contacts table in the db and all rows have both cid and uid populated.

Any clues or a fix?
Thanks

**Comment by bencroker** [comment]
Have you cleared the Craft cache since upgrading? I'm unable to replicate either of these issues, so am guessing this is from old, possibly cached files.

**Comment by robinbeatty** [comment]
Yes cleared cache... 
If I turn off devMode the error fails silently and I am able to continue through both problems.


Here's the trace for the import issue (/admin/campaign/contacts/import):

Twig\Error\RuntimeError: Impossible to access an attribute ("title") on a null variable. in /var/www/html/vendor/putyourlightson/craft-campaign/src/templates/contacts/import/index.twig:113
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'title', Array, 'any', false, false)
#1 /var/www/html/storage/runtime/compiled_templates/ce/ce0b9dbcf8ada1ebae9c8c1d5f9ca9ff2edb6dedc7928e049e2f26bf465ae045.php(101): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'title', Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2a82ed5a8c3c7f3e92818cc2edae609541ef21f129dd75f49b45f4426f684438->doDisplay(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#5 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('campaign/contac...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate('campaign/contac...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('campaign/contac...', Array, 'cp')
#10 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#11 /var/www/html/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#12 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#14 /var/www/html/web/index.php(26): yii\base\Application->run()
#15 {main}


and for the contact entry issue (/admin/campaign/contacts/12345)

Twig\Error\RuntimeError: Impossible to access an attribute ("title") on a null variable. in /var/www/html/vendor/putyourlightson/craft-campaign/src/templates/contacts/import/index.twig:113
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/helpers/Template.php(110): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'title', Array, 'any', false, false)
#1 /var/www/html/storage/runtime/compiled_templates/ce/ce0b9dbcf8ada1ebae9c8c1d5f9ca9ff2edb6dedc7928e049e2f26bf465ae045.php(101): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'title', Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2a82ed5a8c3c7f3e92818cc2edae609541ef21f129dd75f49b45f4426f684438->doDisplay(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#5 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('campaign/contac...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/View.php(504): craft\web\View->renderTemplate('campaign/contac...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(56): craft\web\View->renderPageTemplate('campaign/contac...', Array, 'cp')
#10 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#11 /var/www/html/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#12 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#14 /var/www/html/web/index.php(26): yii\base\Application->run()
#15 {main}

**Comment by robinbeatty** [comment]
Don't know if relevant but the Campaign plugin has been in use on this application since Craft 3.0.0

**Comment by bencroker** [comment]
Thanks for the details. Fixed in https://github.com/putyourlightson/craft-campaign/commit/bb81ed777d4dd35f0e79186b66434cc16783b5e6 and https://github.com/putyourlightson/craft-campaign/commit/b0b72c3dc4aae91dfaf1da64f0e44aa906e12ee3 for the next release. If you'd like to help test then you can change the `putyourlightson/craft-campaign` requirement in your project's `composer.json` file to "`dev-develop as 2.3.1`" and run `composer update`.

**Comment by robinbeatty** [comment]
Great work, thanks a million. Yes will pull the dev branch :)

**Comment by robinbeatty** [comment]
I know I should have posted these as two separate issues... but just to confirm issue 1 (the import tab page) seems to be fixed in `dev-develop as 2.3.1`, cheers. 

Issue 2 – the contact detail page, still throwing error (as above)

**Comment by robinbeatty** [comment]
Twig\Error\RuntimeError: Variable "contactId" does not exist. in /var/www/html/vendor/putyourlightson/craft-campaign/src/templates/reports/contacts/_includes/campaign-activity.twig:41
Stack trace:
#0 /var/www/html/storage/runtime/compiled_templates/dc/dc59aa531c94ae34e30bf506f9c6f5f2da68b8ccf9659b1f7a33d55e0c8225ca.php(182): __TwigTemplate_e94d742b4106187b3aa16844fce8e2bf985979a2452ed89717f589988ef51ef0->{closure}()
#1 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_e94d742b4106187b3aa16844fce8e2bf985979a2452ed89717f589988ef51ef0->doDisplay(Array, Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/storage/runtime/compiled_templates/9b/9b217dd91f75081bcb70faa2fe4116fa9eeb14f51da731a85cf297c2a7b6c67c.php(178): Twig\Template->display(Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_85c73dd89e41a71a4c5f9f5c474f59684fdcf8c52b698d80e082a5a9f3c5b059->doDisplay(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#7 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#8 /var/www/html/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/View.php(451): Twig\Environment->render('campaign/report...', Array)
#10 /var/www/html/vendor/putyourlightson/craft-campaign/src/fieldlayoutelements/reports/ContactReportFieldLayoutElement.php(26): craft\web\View->renderTemplate('campaign/report...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(738): putyourlightson\campaign\fieldlayoutelements\reports\ContactReportFieldLayoutElement->formHtml(Object(putyourlightson\campaign\elements\ContactElement), false)
#12 /var/www/html/vendor/craftcms/cms/src/web/View.php(1605): craft\models\FieldLayout->craft\models\{closure}()
#13 /var/www/html/vendor/craftcms/cms/src/models/FieldLayout.php(737): craft\web\View->namespaceInputs(Object(Closure), NULL)
#14 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(745): craft\models\FieldLayout->createForm(Object(putyourlightson\campaign\elements\ContactElement), false, Array)
#15 /var/www/html/vendor/craftcms/cms/src/controllers/ElementsController.php(444): craft\controllers\ElementsController->_prepareEditor(Object(putyourlightson\campaign\elements\ContactElement), true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
#16 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
#17 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(112): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
#18 /var/www/html/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#19 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1098): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#20 /var/www/html/vendor/craftcms/cms/src/web/Response.php(286): yii\web\Response->prepare()
#21 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#22 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#23 /var/www/html/web/index.php(26): yii\base\Application->run()
#24 {main}

**Comment by bencroker** [comment]
I can't replicate that issue, have you tried clearing the template caches (the stack trace is showing a compiled template this time)? And is there anything out of the ordinary about this specific contact?

**Comment by bencroker** [comment]
Any update on this?

**Comment by robinbeatty** [comment]
It seems to be that vendor/putyourlightson/craft-campaign/src/templates/reports/contacts/_includes/campaign-activity.twig is not receiving the contactId variable for some contacts... I can't see why this is.

If I change the variable to contact.id (rather than contactId) it's fine... should it just be that??

**Comment by robinbeatty** [comment]
i.e. the contact object is available in the parent template .../_includes/report.twig

**Comment by bencroker** [comment]
There must be some edge case at play here. I've switched it to use `contact.id` in https://github.com/putyourlightson/craft-campaign/commit/c16faffddafa47243cc5e31c05381cd5b35ed11c and released in 2.3.1.
